/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package btree;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Collections;

public class App {


    public static void main(String[] args) {
        System.out.println("START!");
        BTMap<Integer,Integer> m = new BTMap<>();

        //testRemove(m);
        //testRemove2(m);
        testRemove3(m);
    }

    static void testRemove1(BTMap<Integer, Integer> m) {
        //var keys = Arrays.asList(10, 1);
        var keys = Arrays.asList(3, 8, 1, 0);

        System.out.println(keys);

        for (int i = 0; i < keys.size(); i++) {
            m.insert(keys.get(i), i);
        }

        System.out.println(m);

        m.remove(0);

        System.out.println(m);
        
        m.remove(1);

        System.out.println(m);
    }

    static void testRemove2(BTMap<Integer, Integer> m) {
        //var keys = Arrays.asList(10, 1);
        var keys = Arrays.asList(3, 8, 1, 0);

        System.out.println(keys);

        for (int i = 0; i < keys.size(); i++) {
            m.insert(keys.get(i), i);
        }

        System.out.println(m);

        m.remove(8);

        System.out.println(m);


    }

    static void testRemove3(BTMap<Integer, Integer> m) {
        //var keys = Arrays.asList(10, 1);
        var keys = Arrays.asList(3, 8, 1, 0, -1, 10, 5);

        System.out.println(keys);

        for (int i = 0; i < keys.size(); i++) {
            m.insert(keys.get(i), i);
        }

        System.out.println(m);

        m.remove(0);

        System.out.println(m);

        m.remove(8);

        System.out.println(m);

        m.remove(3);
        System.out.println(m);
    }


    static List<Integer> getRandomKeys(int n) {
        List<Integer> keys = new ArrayList<>();


         for (int i = 0; i < n; i++) {
            keys.add(i);
         }

         Collections.shuffle(keys);
        return keys;
    }

    static List<Integer> getTestKeys() {
        //var list = Arrays.asList(10, 1);
        //var list = Arrays.asList(3, 8, 1);
        //var list = Arrays.asList(3, 8, 1, 9, 2);
        //var list = Arrays.asList(3, 8, 1, 9, 2, 4);
        //var list = Arrays.asList(3, 8, 1, 9, 2, 4, 0);
        var list = Arrays.asList(3, 8, 1, 9, 2, 4, 0, 5);

        return list;
    }
}
